Updates to the sparql provider to match the mainstem query
internetofwater/reference.geoconnex.us pull request #22
Opened 2024-09-12 20:11 UTC by C-Loftus

2024-09-16 14:02 UTC, C-Loftus commented on docker-compose.yml
needed for psql

2024-09-16 14:03 UTC, C-Loftus commented on pygeoapi-skin-dashboard/templates/collections/items/item.html
> +        {% endif %}
This was coming from the work in the previous PR. Unclear if this should be undone

2024-09-16 14:04 UTC, C-Loftus commented on pygeoapi.config.yml
> +    #         name: Intersector
coming from the previous PR

2024-09-16 14:05 UTC, C-Loftus commented on docker-compose.yml
> +      - ./pygeoapi.config.yml:/pygeoapi/local.config.yml
I feel it is easier to iterate on by having it as a volume instead of copied in.

2024-09-16 14:16 UTC, webb-ben requested changes

2024-09-16 14:16 UTC, webb-ben commented on pygeoapi-skin-dashboard/templates/jsonld/hu06.jsonld
Revert changes here

2024-09-16 14:16 UTC, webb-ben commented on pygeoapi-skin-dashboard/templates/collections/items/item.html
Revert changes here

2024-09-16 14:16 UTC, webb-ben commented on Dockerfile
Revert changes here

2024-09-16 14:16 UTC, webb-ben commented on docker-compose.yml
> +      - POSTGRES_DB=${POSTGRES_DB}
```suggestion
```
Put these in .env

2024-09-16 14:16 UTC, webb-ben commented on pygeoapi.config.yml
> +    #         name: Intersector
```suggestion
    intersector:
        type: process
        processor:
            name: pygeoapi_plugins.process.intersect.IntersectionProcessor
```

2024-09-16 14:16 UTC, webb-ben commented on pygeoapi.config.yml
Can you fix the indentation here so I can better see the diff?

2024-09-16 15:54 UTC, C-Loftus commented
@webb-ben updated the code to reflect your requests. 


sparql provider uses the latest mainstem query I was working on [here](https://graph.geoconnex.us/sparql?name=&infer=true&sameAs=true&query=PREFIX%20schema%3A%20%3Chttps%3A%2F%2Fschema.org%2F%3E%0APREFIX%20gsp%3A%20%3Chttp%3A%2F%2Fwww.opengis.net%2Font%2Fgeosparql%23%3E%0APREFIX%20wiki%3A%20%3Chttps%3A%2F%2Fwww.wikidata.org%2Fwiki%2F%3E%0APREFIX%20hyf%3A%20%3Chttps%3A%2F%2Fwww.opengis.net%2Fdef%2Fschema%2Fhy_features%2Fhyf%2F%3E%0APREFIX%20xsd%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%3E%0APREFIX%20rdf%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%0A%0ASELECT%20DISTINCT%20%0A%3Fmainstem%20%0A%3FmonitoringLocation%20%0A%3FsiteName%20%0A%3FdatasetDescription%20%0A%3Ftype%0A%3Furl%0A%3FvariableMeasured%0A%3FvariableUnit%0A%3FmeasurementTechnique%0A%3FtemporalCoverage%0A%3FdistributionName%0A%3FdistributionURL%0A%3FdistributionFormat%0A%3Fwkt%0AWHERE%20%7B%0A%20%20%20%20VALUES%20%3Fmainstem%20%7B%20%3Chttps%3A%2F%2Fgeoconnex.us%2Fref%2Fmainstems%2F29559%3E%20%7D%0A%20%20%20%20%0A%20%20%20%20%23%20location%20info%0A%20%20%20%20%3FmonitoringLocation%20hyf%3AHydroLocationType%20%3Ftype%3B%0A%20%20%20%20%09%09%09%09%20%20%20%20hyf%3AreferencedPosition%2Fhyf%3AHY_IndirectPosition%2Fhyf%3AlinearElement%20%3Fmainstem%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20schema%3AsubjectOf%20%3Fdataset%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20gsp%3AhasGeometry%2Fgsp%3AasWKT%20%3Fwkt%20.%0A%0A%20%20%20%20%23%20dataset%20info%0A%20%20%20%20%3Fdataset%20%20schema%3AvariableMeasured%20%3Fvar%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20schema%3Aurl%20%3Furl%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20schema%3Adistribution%20%3Fdistribution%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20schema%3Adescription%20%3FdatasetDescription%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20schema%3AtemporalCoverage%20%3FtemporalCoverage%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20schema%3Aname%20%3FsiteName%20.%0A%20%20%20%20%0A%20%20%20%20%23%20variable%20metadata%0A%20%20%20%20%3Fvar%20schema%3Aname%20%3FvariableMeasured%3B%0A%20%20%20%20%20%20%20%20%20schema%3AunitText%20%3FvariableUnit%3B%0A%20%20%20%20%20%20%20%20%20schema%3AmeasurementTechnique%20%3FmeasurementTechnique%20.%0A%20%20%20%20%0A%20%20%20%20%23%20Dataset%20distribution%20%2F%20download%20info%0A%20%20%20%20%3Fdistribution%20schema%3Aname%20%3FdistributionName%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20schema%3AcontentUrl%20%3FdistributionURL%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20schema%3AencodingFormat%20%3FdistributionFormat.%0A%20%20%0A%7D%0ALIMIT%2010%0A)

2024-09-17 13:34 UTC, webb-ben approved these changes

2024-09-17 13:35 UTC, merged